development:
  google_maps_api_key: AIzaSyA054BSC0zknu-p4qgsdlCL2ynyEfCCEw0
  smtp_domain: mail.rediscovermylife.org
  smtp_user_name: locator@rediscovermylife.org
  smtp_password: VBcent900!
production:
  google_maps_api_key: AIzaSyA054BSC0zknu-p4qgsdlCL2ynyEfCCEw0
  smtp_domain: 'locator.rediscovermylife.org'
  smtp_user_name: ENV['SMTP_USER_NAME']
  smtp_password: ENV['SMTP_PASSWORD']
  secret_key_base: 4750d9615136b6b6dff83b177e9d942c284a86a877ab2daf7a409b067528dea53a4ebd04c61d0689ca4e50d7794cd92cd998ebf9b3eb24f6d710562720a1c1dc
